version: '3.4'

services:
  sensorwebapi:
    image: sensorwebapi:dev
    container_name: SensorWebApi
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SensorWebApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sensorwebapi$
    volumes:
      - E:\projetos\junior-analyst\SensorWebApp\SensorWebApi:/app
      - E:\projetos\junior-analyst\SensorWebApp:/src
      - C:\Users\Joao Vítor\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_sensorwebapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sensorwebapi$ \"/app/bin/Debug/netcoreapp2.1/SensorWebApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  sensorwebapp:
    image: sensorwebapp:dev
    container_name: SensorWebApp
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SensorWebApp"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sensorwebapp$
    volumes:
      - E:\projetos\junior-analyst\SensorWebApp\SensorWebApp:/app
      - E:\projetos\junior-analyst\SensorWebApp:/src
      - C:\Users\Joao Vítor\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_sensorwebapp$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sensorwebapp$ \"/app/bin/Debug/netcoreapp2.1/SensorWebApp.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
